package Project_2241016145;

public class Data {
    protected static String nameList [] = {"Yurem Villarreal","Hazel Travis", "Kaya Leach", "Reid Clarke", "Ashanti Mayo", "Cierra Frazier",
            "Salvatore Fry", "Vance Hancock", "Braydon Lozano", "Everett Hart", "Harper Shields","Armani Richards","Abdullah Barker",
            "Gracie Sims", "Davis Stephenson", "Isabella Cross", "Chanel Jimenez", "Penelope Robertson", "Lilian Roy", "Gideon Marquez",
            "Baron Horton", "Charles Odonnell", "Edith Bush", "Warren Banks", "Jamison Waters", "April Hodges", "Gerald Hendrix",
            "Zaniyah Mercer", "Amya Palmer", "Myah Abbott","Amaris Mata", "Ryann Rivera", "Julian Valdez","Dakota Acosta", "Desiree Hardy",
            "Molly Osborn", "Clara Crawford", "Yair Crane", "Aden Small", "Kendall Wilkinson", "Kenya Cox", "Kade Gross", "Presley Hoffman",
            "Camila Morse", "Marely Frazier", "Abagail Lang", "Damien Lowery", "Seth Merritt", "Yosef Mercado", "Emelia Prince", "Sai Mander",
            "Runjhun Ramroop", "Lakshmi Mitra", "Nirmal Rai", "Ajay Sunder", "Basanti Anand", "Taahid Rout", "Urmila Philip", "Virat Gupta",
            "Naina Mani", "Yasmin Devi", "Kalpana Chad", "Umar Chowdhury", "Pranab Baral", "Aruna Badami", "Payal Mathur", "Rohini Sethi",
            "Venkat Jani", "Raghavan Murty", "Bharat Somani", "Nirmal Tak", "Dipti Karan", "Karim Pillay", "Rupal Sabharwal", "Ratan Agrawal",
            "Gowri Narine", "Sushmita Ray", "Trishana Naruka", "Mukul Rampersaud", "Ratan Dada", "Hanuman Aggarwal", "Bhaagyasree Chahal",
            "Rita Tailor", "Kunti Vyas", "Kailash Sankaran", "Ritika Sarma", "Megha Badal", "Aarushi Aurora", "Leelawati Krishnan", "Kalyan Narain",
            "Jawahar Mane", "Bhanupriya Gour", "Ishat Lata", "Urmila Munshi", "Aarti Nayak", "Balaji Boase", "Neela Sharma", "Aayushi Yogi",
            "Ratan Mishra", "Komal Bassi"};

    protected static String addressList [] = {"10458 Damien View, Apt. 518, 67679-1681, Beahanmouth, Missouri, United States","253 Judge Place, Suite 298, 13145, Bashirianport, Maine, United States",
            "6687 Hand Locks, Apt. 587, 96088-1799, Port Giuseppe, Maine, United States", "7433 Parisian Fork, Apt. 955, 90556-5900, Cadenport, Maine, United States",
            "26602 Rutherford Mount, Apt. 659, 50755-9613, Vedafurt, Oklahoma, United States", "73365 Ocie Ramp, Suite 376, 26881, South Anabelshire, New Mexico, United States",
            "Piazza Venezia 20, Piano 5, Piano 1, 41140, Gianni umbro, Latina, Italy", "Borgo D'Orazio 9, Appartamento 89, Appartamento 45, 55828, Bortolo terme, Caserta, Italy",
            "Borgo Semiramide 3, Piano 5, 18570, Dragoni calabro, Caltanissetta, Italy", "Rotonda Pancrazio 42, Appartamento 95, 36844, Daciano a mare, Monza e della Brianza, Italy",
            "Borgo Socrate 7, Piano 4, Piano 4, 19008, San Albina, Campobasso, Italy", "Piazza Gentili 568, Appartamento 79, 03533, D'Orazio salentino, Benevento, Italy",
            "Erftstr. 48, 7 OG, 22869, Lienshöftstadt, Thüringen, Germany","Billrothstr. 28c, Zimmer 723, 01328, Dahmenstadt, Berlin, Germany",
            "Syltstr. 8, Apt. 332, 67716, West Janisscheid, Hessen, Germany", "Moosweg 85a, Apt. 391, 10695, Alt Thiesstadt, Hamburg, Germany",
            "Ruhlachplatz 459, 5 OG, 91908, Löwastadt, Nordrhein-Westfalen, Germany","Wilhelm-Hastrich-Str. 10b, 4 OG, 96398, Klaraburg, Bremen, Germany",
            "97 Mitchell Court, Apt. 984, 5330, Zacharyburgh, Queensland, Australia", "300 Waters Way, Suite 184, 5381, New Layla, Northern Territory, Australia",
            "7202 Elizabeth Square, Suite 876, 8062, South Ellie, South Australia, Australia", "4833 Lockman Pass, Suite 188, 1110, Champlinville, Western Australia, Australia",
            "046 Violet Way, Apt. 278, 7282, Isabelfurt, South Australia, Australia", "69 Victoria Street, Suite 301, 6905, West Darcyville, Northern Territory, Australia",
            "1616 Leilani Court, Suite 349, 1187, Horw, Fribourg, Switzerland","3138 Jenkins Brook, Suite 943, 7400, La Chaux-de-Fonds, Soleure, Switzerland",
            "37984 Lenna Via, Apt. 079, 5301, Le Grand-Saconnex, Argovie, Switzerland", "0500 Padberg Bypass, Suite 955, 6462, Arth, Schwyt, Switzerland",
            "2032 Thompson Route, Suite 996, 7513, Bienne, Schaffhouse, Switzerland", "406 Weber Island, Apt. 817, 9321, Écublens, Zurich, Switzerland",
            "9 Quai d'Orsel, 1 étage, 74965, Cergy, Nord-Pas-de-Calais, France","8 Rue d'Abbeville, 3 étage, 48910, Vénissieux, Poitou-Charentes, France",
            "9 Boulevard des Rosiers, 6 étage, 77862, Avignon, Auvergne, France","6103 Allée Saint-Dominique, 0 étage, 01478, Chambéry, Auvergne, France",
            "9970 Quai de Seine, 3 étage, 58477, Le Tampon, Languedoc-Roussillon, France","201 Boulevard des Rosiers, 1 étage, 08115, Nîmes, Île-de-France, France",
            "056 Goldner Ports, Apt. 383, J3T 2Z9, South Claudineshire, Alberta, Canada","4700 Kris View, Apt. 691, P0B 9W7, Port Abe, Saskatchewan, Canada",
            "41903 Kylie Road, Suite 548, R7Q 2Y2, Patton, Quebec, Canada","001 Edgardo Way, Apt. 812, K9X 6V6, Ardithfurt, Saskatchewan, Canada",
            "73538 Quentin Pass, Suite 047, C0U 7O1, New Ethanmouth, Yukon, Canada","81550 Herman Locks, Apt. 126, Y2J 8J3, Eltonport, Quebec, Canada",
            "3048 Reilly Lake, Suite 877, G8Z 5G9, Lehnerport, New Brunswick, Canada", "403 Nelson Valley, Suite 181, L1V 8W5, Port Kyleton, Newfoundland and Labrador, Canada",
            "47119 Marquis Run, Suite 346, 52255, Port Chadrick, Tennessee, South Africa", "1849 Emmet Avenue, Apt. 339, 13701, Margaretview, Tennessee, South Africa",
            "3951 Tracy Course, Suite 642, 35475, East Alisha, Kentucky, South Africa", "8359 Tessie Stream, Suite 162, 4768, North Geneville, Arizona, South Africa",
            "85274 Mack Wells, Apt. 662, 2662, Macejkovicborough, Georgia, South Africa","493 Beahan Roads, Suite 980, 4098, Dooleyview, Maine, South Africa",
            "Street: E, mankoli naka, County/Department: Bhiwandi, State/Region: Maharashtra, Postcode: 421202, Country: India",
            "Street: Karimabad Cooperative Society, Karimabad Cooperative Society, Chirag Ali Lane, Neighbourhood: Gun Foundry, Suburb/City: Ward 78 Gunfoundry, Hyderabad, County/Department: Nampally mandal, State/Region: Telangana, Postcode: 500001, Country: India",
            "Street: Mary Immaculate Girls' High School, church road santacruz (east), Church Road , Neighbourhood: Kolivery Village, Suburb/City: H/E Ward, Mumbai , State/Region: Maharashtra , Postcode: 400029 , Country: India",
            "Street: 68, 4th Avenue, Suburb/City: Bellanduru, Bengaluru, County/Department: Bangalore South, State/Region: Karnataka, Postcode: 560035, Country: India",
            "Street: Jamnabai Narsee School, Narsee Monjee Bhavan 7, NS Road No 6 Suburb/City: Juhu, Mumbai State/Region: Maharashtra Postcode: 400058 Country: India",
            "Street: 179, 5th Main Road Neighbourhood: Defence ColonySuburb/City: Hoysala Nagara, BengaluruCounty/Department: Bangalore East State/Region: Karnataka Postcode: 560038 Country: India",
            "Street: 91, Richmond Road Cycle Path Suburb/City: Ashok Nagar, Bengaluru County/Department: Bangalore North State/Region: Karnataka Postcode: 560025 Country: India",
            "Street: Nice Moment Family Restaurant, Shop No.10 Plot 44 Sector 35D, Ganesh Mandir Road Neighbourhood: Owe Village Suburb/City: Panvel County/Department: Panvel State/Region: Maharashtra Postcode: 410210 Country: India",
            "Street: C, Ghodbunder Service Road County/Department: Thane State/Region: Maharashtra Postcode: 400615 Country: India",
            "Street: BAR OF BURGER, HP PETROL PUMP, HL Parwana Road Neighbourhood: Sector 9 County/Department: Rohini Tehsil State/Region: Delhi Postcode: 110085 Country: India",
            "Street: 5, Road Number 1 Neighbourhood: Prashasan Nagar Suburb/City: Ward 95 Jubilee Hills, Hyderabad County/Department: Shaikpet mandal State/Region: Telangana Postcode: 500110 Country: India",
            "Street: 1, J1 Suburb/City: Sector 25, Gurugram State/Region: Haryana Postcode: 122008 Country: India",
            "Street: 211A, Street number 11 Neighbourhood: South End Park Suburb/City: Ward 11 Nagole, Hyderabad County/Department: Saroornagar mandal State/Region: Telangana Postcode: 500068 Country: India",
            "Street: Amanda-A, A, Canberra Terrace County/Department: Thane State/Region: Maharashtra Postcode: 401302 Country: India",
            "Street: No.15, 2, Mathura Road Suburb/City: Faridabad County/Department: Faridabad State/Region: Haryana Postcode: 121003 Country: India",
            "Street: 117 & 118, Rd Number 3, EPIP Zone, Vydehi Hospital Road Town: Whitefield Suburb/City: Hagadur, Bengaluru County/Department: Bangalore East State/Region: Karnataka Postcode: 560037 Country: India",
            "Street: 11 - 12, Thekedar Surjit Singh Marg Neighbourhood: neighbouhood County/Department: Model Town Tehsil State/Region: Delhi Postcode: 110009 Country: India",
            "Street: Thran, 507, 4th A Cross Road Suburb/City: Kacharkanahalli, Bengaluru County/Department: Bangalore North State/Region: Karnataka Postcode: 560043 Country: India",
            "Street: 395, 11th Cross Road Neighbourhood: Dollar Colony Suburb/City: Nagashettyhalli, Bengaluru County/Department: Bangalore North State/Region: Karnataka Postcode: 560094 Country: India",
            "Street: 515, 16th Cross Road Neighbourhood: LBS Nagar Suburb/City: Hoysala Nagara, Bengaluru County/Department: Bangalore North State/Region: Karnataka Postcode: 560038 Country: India",
            "Street: Analystics BI, 23/1, Hare Krishna Road Neighbourhood: Madhav Nagar Suburb/City: Vasanth Nagar, Bengaluru County/Department: Bangalore North State/Region: Karnataka Postcode: 560001 Country: India",
            "Street: Kedar, H9, Glady's Alwares Avenue Neighbourhood: Nalpada County/Department: Thane State/Region: Maharashtra Postcode: 401302 Country: India",
            "Street: B-30, Ranhola, Najafgarh Nangloi Road Neighbourhood: Baprola County/Department: Punjabi Bagh Tehsil State/Region: Delhi Postcode: 110041 Country: India",
            "Street: Al Khair Restaurant, 20, Sulthanpalya Main Road Neighbourhood: Kanaka Nagar Suburb/City: Vishwanath Nagenahalli, Bengaluru County/Department: Bangalore North State/Region: Karnataka Postcode: 560032 Country: India",
            "Street: 26/3, Tumkur Road Suburb/City: Subramanya Nagar, Bengaluru County/Department: Bangalore North State/Region: Karnataka Postcode: 560055 Country: India",
            "Street: B, Western Express Highway Suburb/City: Goregaon East, Mumbai State/Region: Maharashtra Postcode: 400063 Country: India",
            "Street: Lodhi Garden, Lodhi Road Neighbourhood: Lodhi Colony Suburb/City: New Delhi County/Department: Defence Colony Tehsil State/Region: Delhi Postcode: 110003 Country: India",
            "Street: 62 Milestone, NH 19 Suburb/City: Palwal County/Department: Palwal State/Region: Haryana Postcode: 121102 Country: India",
            "Street: A, Thane Ghodbunder Road County/Department: Thane State/Region: Maharashtra Postcode: 400615 Country: India",
            "Street: SEEPZ Village Bus Stn(Temporary), SEEPZ VILLAGE, Jogeshwari Vikhroli Link Road Neighbourhood: Pratap Nagar Suburb/City: K/E Ward, Mumbai State/Region: Maharashtra Postcode: 400029 Country: India"};

    protected static String jobPosition[] = {"Manager","Senior Engineer","Data Scientist","Data Analyst","Junior Engineer","HR Manager","Project Manager","Web Developer","Marketing Manager","Security Analyst"};

}


